displayName=Custom Projectile Hider
author=Eric
description=Hide specific projectile IDs
tags=projectile,hider,hide
version=
plugins=com.customprojectilehider.CustomProjectileHiderPlugin
build=standard